# Generated by Django 3.0.5 on 2020-06-08 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_friend_current_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
